MOTOR-1068 Tornado no longer supports Python 3.7
mongodb/motor pull request #188
Opened 2022-12-06 16:43 UTC by juliusgeo

2022-12-08 14:22 UTC, blink1073 commented
The Ubuntu 22.04 images do not have MongoDB installed, we'll need to use https://github.com/supercharge/mongodb-github-action#usage.

2022-12-08 14:23 UTC, blink1073 commented
The flake8 url in `.pre-commit-config.yaml` also needs to be updated to `https://github.com/pycqa/flake8`

2022-12-08 17:45 UTC, ShaneHarvey commented
Let's open a new ticket for the github actions change.

2022-12-08 17:45 UTC, ShaneHarvey requested changes

2022-12-08 17:45 UTC, ShaneHarvey commented on .evergreen/config.yml
> -           PYTHON_BINARY: "/opt/python/3.7/bin/python3"
Why remove this?

2022-12-08 17:45 UTC, ShaneHarvey commented on .evergreen/config.yml
> -      - id: "tornado6-py37"
Why remove this?

2022-12-09 21:28 UTC, blink1073 commented
I think we should merge a fix for https://jira.mongodb.org/browse/MOTOR-1073 before merging this one.

2022-12-09 21:31 UTC, ShaneHarvey approved these changes
No need to wait since MOTOR-1073 is unrelated.

2022-12-13 22:04 UTC, merged