MOTOR-1178 Stop using tox labels
mongodb/motor pull request #230
Opened 2023-09-06 00:48 UTC by blink1073

2023-09-07 21:20 UTC, NoahStapp requested changes

2023-09-07 21:20 UTC, NoahStapp commented on tox.ini
We should require `tox>=4.9.0` to ensure the safety of not using labels.

2023-09-08 01:08 UTC, blink1073 commented on tox.ini
Done.  TIL about [Auto-Provisioning](https://tox.wiki/en/latest/user_guide.html#auto-provisioning), which works for tox 3.8.0+

2023-09-08 01:12 UTC, blink1073 commented on tox.ini
Ah, no can do, tox 4.9 only supports Python 3.8+

2023-09-08 18:45 UTC, NoahStapp commented on tox.ini
Then all of our Python 3.7 environments could have tox commands fail silently without the labels. Maybe we delay this change until we drop support for Python 3.8?

2023-09-08 18:52 UTC, blink1073 commented on tox.ini
It would only fail silently if the label was incorrect, no?  But we're using the same labels across Python versions.

2023-09-08 19:58 UTC, NoahStapp commented on tox.ini
But without labels you introduce the possibility of typos or other mistakes to silently fail. With labels, your environments won't run at all if you don't explicitly add a label for them.

2023-09-08 21:03 UTC, blink1073 commented on tox.ini
You're talking about for local development?

2023-09-08 22:20 UTC, NoahStapp commented on tox.ini
By using `tox -m <label>`, we ensure that it fails instantly if the environment does not exist. Since the same behavior only exists for `tox -e <env>` in Python 3.8+, all of our Python 3.7 tests will not fail on nonexistent environment names.

2023-09-08 22:27 UTC, blink1073 commented on tox.ini
And my argument is that we should instead ensure that we are running the same code paths on Python 3.7 and a non-EOL python, thereby avoiding that risk

2023-09-08 22:35 UTC, NoahStapp commented on tox.ini
Ah, I see sorry! Didn't understand your suggestion: is there a way of doing that without manually keeping the 3.7 version in sync?

2023-09-09 01:08 UTC, blink1073 commented on tox.ini
I went down a rabbit hole of trying to get all the tasks to run on 3.7 and 3.12, but I don't think it is worth it, let's just close these tickets.

2023-09-09 01:08 UTC, closed without merging