MOTOR-1163: remove AIOHTTP_NO_EXTENSIONS and test support against Python 3.12
mongodb/motor pull request #255
Opened 2024-02-02 19:25 UTC by Jibola

2024-02-02 20:44 UTC, ShaneHarvey requested changes
Could you schedule the 3.12 aiohttp tests?

2024-02-02 20:44 UTC, ShaneHarvey commented on tox.ini
>  # TODO: Remove as part of MOTOR-1163
We can remove this todo too.

2024-02-05 14:21 UTC, Jibola commented
> Could you schedule the 3.12 aiohttp tests?

Hrm, is there a specific task I needto schedule. I checked evergreen and I see the 3.12 tests already running, as well as the one from the github actions.

https://spruce.mongodb.com/version/65bd41f4a4cf474e8b082ad9/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Emain__ssl~ssl_tox-env~test-py312_os~rhel84%24

2024-02-05 18:31 UTC, blink1073 commented
aiohttp used to be its own test target, it now runs as part of the standard test suite.

2024-02-05 18:32 UTC, blink1073 approved these changes
LGTM!

2024-02-05 19:26 UTC, ShaneHarvey approved these changes

2024-02-06 14:59 UTC, merged